#!name=Soul
#!desc=Soul解锁
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/Plugallery.png
#!homepage=https://yfamilys.com
#!author=89996462


^http[s]?:\/\/(api-chat.soulapp.cn|.*)\/(chat/limitInfo|vip/meet/userInfo|loveBell/queryMatchSpeedupConf) url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/Soul.js
hostname = (.*|api-chat.soulapp.cn)
