[rewrite_local]
# > Apple 网络定位服务 (WLOC) 虚拟定位修正
^https?:\/\/ls\.apple\.com\/gslb\? url script-request-header https://raw.githubusercontent.com/Mygodsss/wang47/main/rewrite/QuantumultX/wloc.js

[mitm]
hostname = ls.apple.com
