[rewrite_local]
# > Apple 网络定位服务 (WLOC) 虚拟定位修正
^https?:\/\/ls\.apple\.com\/gslb\? url script-request-header https://raw.githubusercontent.com/NobyDa/Script/master/Surge/JS/wloc.js

[mitm]
hostname = ls.apple.com
