[general]
server_check_url = http://cp.cloudflare.com/generate_204
dns_exclusion_list = *.cmpassport.com, *.id6.me, *.open.e.189.cn
geo_location_checker = disabled

[dns]
no-ipv6
no-system
server = 223.5.5.5
server = 119.29.29.29
server = https://dns.google/dns-query
server = https://1.1.1.1/dns-query

[policy]
static=🚀 节点选择, direct, proxy, 香港节点, 台湾节点, 狮城节点, 日本节点, 美国节点
static=🤖 人工智能, 🚀 节点选择, direct
static=🪙 加密货币, 台湾节点, 狮城节点, 日本节点, direct
static=📞 谷歌语音, 美国节点, direct
static=🎬 优兔视频, 🚀 节点选择, direct
static=🌐 谷歌服务, 🚀 节点选择, direct
static=🐟 兜底分流, 🚀 节点选择, direct

url-latency-benchmark=香港节点, server-tag-regex=(🇭🇰|港|HK|HongKong), check-interval=600, tolerance=30
url-latency-benchmark=台湾节点, server-tag-regex=(🇹🇼|台|TW|Taiwan), check-interval=600, tolerance=30
url-latency-benchmark=狮城节点, server-tag-regex=(🇸🇬|新|狮|SG|Singapore), check-interval=600, tolerance=30
url-latency-benchmark=日本节点, server-tag-regex=(🇯🇵|日|JP|Japan), check-interval=600, tolerance=30
url-latency-benchmark=美国节点, server-tag-regex=(🇺🇸|美|US|States), check-interval=600, tolerance=40

[server_remote]
https://your-airport.example.com/sub/token=YOUR_TOKEN_HERE, tag=Airport, update-interval=86400, opt-parser=true, enabled=true

[filter_remote]
https://rule-proxy.mygods.workers.dev/qx/all.list, tag=Wang47-Master-Rule, update-interval=86400, opt-parser=true, enabled=true

[filter_local]
ip-cidr, 10.0.0.0/8, direct
ip-cidr, 127.0.0.0/8, direct
ip-cidr, 172.16.0.0/12, direct
ip-cidr, 192.168.0.0/16, direct
geoip, cn, direct
final, 🐟 兜底分流
